[tool.towncrier]
directory = "changelog.d"
filename = "CHANGELOG.md"
start_string = "<!-- towncrier release notes start -->\n"
title_format = "## [{version}] — {project_date}"
issue_format = "{issue}"
orphan_prefix = "+"
underlines = ["", "", ""]

[[tool.towncrier.type]]
directory = "feature"
name = "Added"
showcontent = true

[[tool.towncrier.type]]
directory = "fix"
name = "Fixed"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Changed"
showcontent = true
