package com.lifeops.briefing.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room persistence for a locally-cached FlowSavvy task -- mirrors
 * [NextTask] (see `NextTasksState.kt`) plus the extra fields a durable
 * cache needs that an ephemeral widget-render snapshot doesn't:
 * [completed] and [dueAtEpochMillis] so the app can still answer "what's
 * outstanding, and by when" from the last known-good pull if a network
 * fetch (`LifeOpsComputeWorker`) fails transiently, and [sourceJson] so a
 * later data-gather layer doesn't lose any FlowSavvy field this first cut
 * of the schema didn't anticipate.
 *
 * [id] matches FlowSavvy's own task id ([NextTask.id]) -- the natural
 * primary key, not a synthetic autogenerated one, since this table's whole
 * purpose is "the last known state of THIS specific remote task," and an
 * upsert-by-id is exactly the write pattern a refresh cycle needs (see
 * [TaskCacheDao.upsertAll]).
 *
 * [dueAtEpochMillis], not a raw string: same epoch-millis-for-sortable-
 * queries reasoning as [HistoryEventEntity.timestampEpochMillis] -- a
 * "what's due soon" query needs a real ORDER BY/range-comparable column,
 * and [NextTask.start] is a plain nullable ISO string with no such
 * guarantee today.
 *
 * [sourceJson] is the full raw JSON object FlowSavvy's API returned for
 * this task at fetch time -- deliberately NOT trimmed to just the fields
 * [NextTask]/this entity's own typed columns use, so a future consumer that
 * needs a field this schema didn't foresee (recurrence info, list/priority
 * metadata, etc.) can still recover it without a migration, matching this
 * task's brief ("keep it generic/simple rather than over-fitting to
 * today's exact shapes"). Nullable only for a hand-constructed test/seed
 * row that has no real API payload behind it.
 */
@Entity(tableName = "task_cache")
data class TaskCacheEntity(
    @PrimaryKey val id: String,
    val title: String,
    val dueAtEpochMillis: Long? = null,
    val completed: Boolean = false,
    val sourceJson: String? = null,
)
